# Generated by Django 6.1 on 2026-09-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_warehouse',
            field=models.BooleanField(default=False, help_text='Central storage location — excluded from retail-only pickers (staff assignment, dashboard, reports) but still a valid stock-transfer endpoint.'),
        ),
    ]
