# Generated by Django 6.1 on 2026-09-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_is_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allow_custom_mixes',
            field=models.BooleanField(default=True, help_text='OFF: cashiers can only add colors from the Color Menu catalog at the Tinting Desk — manual HEX/RGB/wheel mixing is locked for them (managers are never restricted).'),
        ),
    ]
