# Generated by Django 6.1 on 2026-09-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_void_reason_sale_voided_at_sale_voided_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money the order discount actually took off — computed, not entered.', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounted_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No discount'), ('percent', 'Percent off'), ('amount', 'Flat amount off')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percent (0-100) or flat amount, depending on discount_type.', max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No discount'), ('percent', 'Percent off'), ('amount', 'Flat amount off')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit, snapshotted when the line was rung up so history stays honest.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net of every discount, before tax.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Charged for this line, after its own discount.', max_digits=10),
        ),
    ]
