# Generated by Django 6.1 on 2026-08-24 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Colorant code, e.g. B, C, E, KX', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('hex_color', models.CharField(help_text='#RRGGBB', max_length=7)),
                ('cost_per_ml', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ColorFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hex_color', models.CharField(help_text='#RRGGBB', max_length=7)),
                ('r', models.PositiveSmallIntegerField(default=0)),
                ('g', models.PositiveSmallIntegerField(default=0)),
                ('b', models.PositiveSmallIntegerField(default=0)),
                ('base_size', models.CharField(choices=[('1L', '1L Base'), ('4L', '4L Base'), ('20L', '20L Drum')], default='4L', max_length=5)),
                ('finish', models.CharField(blank=True, help_text='e.g. Matte, Eggshell, Satin', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_formulas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColorFormulaLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('volume_ml', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.colorformula')),
                ('pigment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formula_lines', to='catalog.pigment')),
            ],
            options={
                'ordering': ['pigment__code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit_label', models.CharField(help_text='e.g. 1 Gal, 4L, 9" Roller', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_tintable', models.BooleanField(default=False, help_text='Can be sent through the Tinting Desk')),
                ('reorder_threshold', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='colorformula',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_formulas', to='catalog.product'),
        ),
    ]
