# Generated by Django 6.1 on 2026-09-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorformula',
            name='code',
            field=models.CharField(blank=True, help_text='e.g. SW-7005, RAL 9010', max_length=30),
        ),
        migrations.AddField(
            model_name='colorformula',
            name='is_catalog_shade',
            field=models.BooleanField(default=False, help_text='Show on the Color Menu as a pre-approved, pickable shade'),
        ),
        migrations.AddField(
            model_name='colorformula',
            name='shade_category',
            field=models.CharField(blank=True, choices=[('pastels', 'Pastels'), ('neutrals', 'Neutrals'), ('earth_tones', 'Earth Tones'), ('bold_accents', 'Bold Accents'), ('exterior_shades', 'Exterior Shades')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='base_type',
            field=models.CharField(blank=True, help_text='Tint-capacity class of this can, e.g. Pastel Base, Deep Base, Neutral Base', max_length=40),
        ),
    ]
