# Generated by Django 6.1 on 2026-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_colorformula_code_colorformula_is_catalog_shade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What one unit costs you. Drives profit / loss reporting — leave 0 if unknown.', max_digits=10),
        ),
    ]
