# Generated by Django 6.1 on 2026-08-30 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_sale_void_reason_sale_voided_at_sale_voided_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LoyaltyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earn', 'Points earned'), ('redeem', 'Points redeemed for credit'), ('spend', 'Store credit spent'), ('adjust', 'Manual adjustment'), ('reversal', 'Reversed (sale voided)')], max_length=20)),
                ('points', models.IntegerField(default=0, help_text='Positive = earned, negative = spent')),
                ('credit_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_entries', to='customers.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to='sales.sale')),
            ],
            options={
                'verbose_name_plural': 'loyalty entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
