# Generated by Django 6.1 on 2026-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_loyalty_points_loyaltyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('regular', 'Regular customer'), ('walkin', 'Walk-in')], default='regular', help_text='Walk-ins are name-only: no phone, loyalty or store credit.', max_length=10),
        ),
    ]
