# Generated by Django 6.1 on 2026-09-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0003_branch_is_warehouse'),
        ('inventory', '0002_supplier_stocktransfer_decided_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PigmentStockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ml', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigment_stock_levels', to='core.branch')),
                ('pigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.pigment')),
            ],
            options={
                'ordering': ['branch__name', 'pigment__code'],
                'unique_together': {('branch', 'pigment')},
            },
        ),
    ]
