# Generated by Django 6.1 on 2026-09-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_pigmentstocklevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % the vendor quoted for this line, entered by hand from their invoice/quote.', max_digits=5),
        ),
    ]
