# Generated by Django 6.1 on 2026-09-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseorderline_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='subtotal - standard_discount - manual_discount. What you actually owe the vendor.', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manual_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Extra discount off this specific invoice, entered by hand from the vendor's paperwork.", max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='standard_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Auto-applied from the vendor's default discount % at the time of the last recalculation.", max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of every line (quantity x unit cost), before any discount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text="This vendor's standing discount — auto-applied to the subtotal of every new purchase order.", max_digits=5),
        ),
    ]
